# Generated by Django 3.0.3 on 2020-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201028_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_description',
            field=models.CharField(default='sdf', max_length=150),
            preserve_default=False,
        ),
    ]
