# Generated by Django 3.0.3 on 2020-10-23 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20201016_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
